Disable inclusion of netifaces module alongside scapy, as in some cases scapy3k encounters exceptions.
  File "/Users/DarrenSpruell/devel/external/ampt-generator/ampt_generator/__init__.py", line 15, in <module>
    from . import api
  File "/Users/DarrenSpruell/devel/external/ampt-generator/ampt_generator/api.py", line 11, in <module>
    from . import app, packetgen
  File "/Users/DarrenSpruell/devel/external/ampt-generator/ampt_generator/packetgen.py", line 7, in <module>               from scapy.all import IP, TCP, UDP, send, conf
  File "/Users/DarrenSpruell/venv.d/ampt-generator/lib/python3.6/site-packages/scapy/all.py", line 25, in <module>
    from .route import *                                                                                                 File "/Users/DarrenSpruell/venv.d/ampt-generator/lib/python3.6/site-packages/scapy/route.py", line 163, in <module>
    conf.route=Route()
  File "/Users/DarrenSpruell/venv.d/ampt-generator/lib/python3.6/site-packages/scapy/route.py", line 22, in __init__       self.resync()
  File "/Users/DarrenSpruell/venv.d/ampt-generator/lib/python3.6/site-packages/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/Users/DarrenSpruell/venv.d/ampt-generator/lib/python3.6/site-packages/scapy/arch/unix.py", line 82, in read_ro
utes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/Users/DarrenSpruell/venv.d/ampt-generator/lib/python3.6/site-packages/scapy/arch/__init__.py", line 52, in get
_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
TypeError: a bytes-like object is required, not 'NoneType'

Reference https://github.com/phaethon/scapy/issues/206 for information on documented failure case.